version: '3.8'

services:
  app:
    build: .
    ports:
      - "1605:8088"
    env_file: 
      - .env
    volumes:
      - /Users/dvdelbaz/Documents/mini-projects/fastify-postgres-docker:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /Users/dvdelbaz/Documents/mini-projects/fastify-postgres-docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
